#!/bin/bash

# REX Control System installer
# HW specific operations - UniPi

if [ "$EUID" -ne 0 ]
  then echo "Please run this script as root"
  exit
fi

#--- UniPi specific operations ---
echo Enabling I2C bus...
cp /boot/config.txt /boot/config.txt.rexbak
echo 'dtparam=i2c_arm=on' >> /boot/config.txt
echo 'dtparam=i2c_baudrate=400000' >> /boot/config.txt
apt-get install -y i2c-tools
echo 'i2c-dev' >> /etc/modules

echo Installing OWFS \(1-Wire\)...
apt-get install -y owserver ow-shell rex-owsdrvt
cp /etc/owfs.conf /etc/owfs.conf.rexbak
echo '!server: server = 127.0.0.1:4304' > /etc/owfs.conf
echo 'allow_other' >> /etc/owfs.conf
echo 'server: port = 127.0.0.1:4304' >> /etc/owfs.conf
echo 'server: i2c = ALL:ALL' >> /etc/owfs.conf
echo 'timeout_volatile = 2' >> /etc/owfs.conf

echo Enabling the RTC chip...
RTCINITFNAME="/etc/rexcore/rexcore.env.d/80-rtcunipi.sh"
echo 'dtoverlay=i2c-rtc,mcp7941x' >> /boot/config.txt
echo '#!/bin/bash' > $RTCINITFNAME
echo '#This is to enable the RTC chip prior to starting the RexCore runtime core.' >> $RTCINITFNAME
echo 'echo mcp7941x 0x6f > /sys/bus/i2c/devices/i2c-1/new_device' >> $RTCINITFNAME
echo 'sleep 2' >> $RTCINITFNAME
echo '#This is to load system time from RTC chip prior to starting the RexCore runtime core.' >> $RTCINITFNAME
echo 'hwclock --hctosys' >> $RTCINITFNAME
echo 'service ntp start' >> $RTCINITFNAME 
chmod +x $RTCINITFNAME

echo Removing fake-hwclock...
apt-get purge -y fake-hwclock
update-rc.d -f fake-hwclock remove
apt-get autoremove -y

if cat /etc/*-release | grep VERSION= | grep -iq Wheezy; then
  rm /etc/cron.hourly/fake-hwclock
  rm /etc/init.d/fake-hwclock
fi

# Disabling ntp service autostart. It is started by the RTC initialization script.
update-rc.d ntp disable

echo ' '
echo 'REX for Raspberry Pi with UniPi add-on board was installed.'
echo ' '
echo '!!! REBOOT IS REQUIRED !!!'
echo ' '

read -p "Is it OK to reboot now? [y/N] " -n 1 -r
echo ' '
if [[ $REPLY =~ ^[Yy]$ ]]
then
    reboot
else
  echo 'Remember to reboot your Raspberry Pi at your earliest convenience.'
fi
echo ' '