#!/bin/bash

# REXYGEN installer
# HW specific operations - UniPi

if [ "$EUID" -ne 0 ]
  then echo "Please run this script as root"
  exit
fi

#--- UniPi specific operations ---
echo Enabling I2C bus...
cp /boot/config.txt /boot/config.txt.rexbak
if ! grep -q '^dtparam=i2c_arm=on' /boot/config.txt
    then echo 'dtparam=i2c_arm=on' >> /boot/config.txt
fi
if ! grep -q '^dtparam=i2c_baudrate=400000' /boot/config.txt
    then echo 'dtparam=i2c_baudrate=400000' >> /boot/config.txt
fi
echo "i2c-dev" > /etc/modules-load.d/i2cdev.conf
apt install -y i2c-tools

echo Installing OWFS \(1-Wire\)...
apt install -y owserver ow-shell rex-owsdrvt
cp /etc/owfs.conf /etc/owfs.conf.rexbak
echo '!server: server = localhost:4304' > /etc/owfs.conf
echo 'allow_other' >> /etc/owfs.conf
echo 'server: port = localhost:4304' >> /etc/owfs.conf
echo 'server: i2c = ALL:ALL' >> /etc/owfs.conf
echo 'timeout_volatile = 2' >> /etc/owfs.conf

echo Enabling the RTC chip...
if ! grep -q '^dtoverlay=i2c-rtc,mcp7941x' /boot/config.txt
    then echo 'dtoverlay=i2c-rtc,mcp7941x' >> /boot/config.txt
fi
sed -i '/^if \[ -e \/run\/systemd\/system/,/^fi/s/^/#/'  /lib/udev/hwclock-set

echo Removing fake-hwclock...
apt purge -y fake-hwclock
update-rc.d -f fake-hwclock remove
apt autoremove -y

echo ' '
echo 'Runtime modules of REXYGEN for Raspberry Pi with UniPi add-on board were successfully installed.'
echo ' '
echo '!!! REBOOT IS REQUIRED !!!'
echo ' '
echo 'Afterwards you will be able to program your Raspberry Pi using REXYGEN Studio.'
echo ' '
# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "The IP address of this device is %s\n" "$_IP"
fi
echo ' '

read -p "Is it OK to reboot now? [y/N] " -n 1 -r
echo ' '
if [[ $REPLY =~ ^[Yy]$ ]]
then
    reboot
else
  echo 'Remember to reboot your Raspberry Pi at your earliest convenience.'
fi
echo ' '